# Generated by Django 2.0.3 on 2018-03-29 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador', models.CharField(max_length=200)),
                ('pa', models.CharField(max_length=200)),
                ('inclusao', models.DateField(verbose_name='Date')),
                ('observacao', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Cooperativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperativa', models.CharField(max_length=200)),
                ('agencia', models.CharField(max_length=200)),
                ('solicitante', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.CharField(max_length=50, null=True)),
                ('celular', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresarial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(max_length=200)),
                ('qnt_local_risco', models.IntegerField()),
                ('IS', models.FloatField()),
                ('renovacao_cia', models.CharField(max_length=200)),
                ('final_vigencia', models.DateField(verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Frota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_leve', models.BooleanField(default=False)),
                ('tipo_pesado', models.BooleanField(default=False)),
                ('qnt_itens_seg', models.IntegerField()),
                ('renovacao_cia', models.CharField(max_length=200)),
                ('final_vigencia', models.DateField(verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ramo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('Empresarial', 'Empresarial'), ('Vida', 'Vida'), ('Frota', 'Frota')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Segurado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.CharField(max_length=50, null=True)),
                ('celular', models.CharField(max_length=50, null=True)),
                ('cnpj', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=200)),
                ('municipio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IS', models.FloatField()),
                ('mercadoria_transportada', models.CharField(max_length=200)),
                ('renovacao_cia', models.CharField(max_length=200)),
                ('final_vigencia', models.DateField(verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='TransporteCobertura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Acidente', 'Acidente'), ('Roubo', 'Roubo')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransporteTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Transportadora', 'Transportadora'), ('Comum', 'Empresa Comum'), ('Nacional', 'Nacional'), ('Internacional', 'Internacional')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VeiculoTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Leve', 'Leve'), ('Pesado', 'Pesado')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VidaGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GLOBAL', 'Global'), ('ESPECIFICA', 'Específica')], max_length=20)),
                ('IS', models.FloatField()),
                ('atividade', models.CharField(max_length=200)),
                ('qnt_vida_seg', models.IntegerField()),
                ('renovacao_cia', models.CharField(max_length=200)),
                ('final_vigencia', models.DateField(verbose_name='Date')),
            ],
        ),
        migrations.AddField(
            model_name='transporte',
            name='cobertura',
            field=models.ManyToManyField(to='agendamento.TransporteCobertura'),
        ),
        migrations.AddField(
            model_name='transporte',
            name='tipo_empresa',
            field=models.ManyToManyField(to='agendamento.TransporteTipo'),
        ),
        migrations.AddField(
            model_name='produto',
            name='ramo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.Ramo'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='cooperativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.Cooperativa'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='ramo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.Ramo'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='segurado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.Segurado'),
        ),
    ]
