# Generated by Django 2.0.3 on 2018-03-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200)),
                ('agencia', models.CharField(max_length=200)),
                ('inicio_vigencia', models.DateField(verbose_name='Date')),
            ],
        ),
    ]
