# Generated by Django 2.0.3 on 2018-03-29 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frota',
            name='segurado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agendamento.Segurado'),
            preserve_default=False,
        ),
    ]
