# Generated by Django 2.0.3 on 2018-04-18 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='final_vigencia',
        ),
    ]
