# Generated by Django 2.0.3 on 2018-04-18 04:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_remove_agendamento_final_vigencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='final_vigencia',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
    ]
