# Generated by Django 2.0.3 on 2018-03-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_frota_segurado'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='bem',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
