# Generated by Django 2.0.3 on 2018-04-20 02:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0003_agendamento_final_vigencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporte',
            name='cobertura',
        ),
        migrations.RemoveField(
            model_name='transporte',
            name='tipo_empresa',
        ),
        migrations.AddField(
            model_name='transporte',
            name='cobertura_acidente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transporte',
            name='cobertura_roubol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transporte',
            name='protocol',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transporte',
            name='tipo_comum',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transporte',
            name='tipo_internacional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transporte',
            name='tipo_nacional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transporte',
            name='tipo_transportadora',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ramo',
            name='nome',
            field=models.CharField(choices=[('Empresarial', 'Empresarial'), ('Vida', 'Vida'), ('Frota', 'Frota'), ('Transporte', 'Transporte'), ('Vida', 'Vida')], max_length=20),
        ),
    ]
