# Generated by Django 2.0.3 on 2018-04-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0003_agendamento_bem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segurado',
            name='municipio',
            field=models.CharField(max_length=100),
        ),
    ]
