# Generated by Django 2.0.3 on 2018-04-20 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0004_auto_20180419_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transporte',
            old_name='cobertura_roubol',
            new_name='cobertura_roubo',
        ),
    ]
