# Generated by Django 2.0.3 on 2018-04-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0004_auto_20180410_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segurado',
            name='id',
        ),
        migrations.AlterField(
            model_name='segurado',
            name='cnpj',
            field=models.CharField(max_length=14, primary_key=True, serialize=False),
        ),
    ]
