# Generated by Django 2.0.3 on 2018-04-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0005_auto_20180410_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='segurado',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='segurado',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
