# Generated by Django 2.0.3 on 2018-04-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0005_auto_20180420_0145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VidaGrupo',
            new_name='Vida',
        ),
        migrations.AlterField(
            model_name='ramo',
            name='nome',
            field=models.CharField(choices=[('Empresarial', 'Empresarial'), ('Vida', 'Vida'), ('Frota', 'Frota'), ('Transporte', 'Transporte')], max_length=20, unique=True),
        ),
    ]
