# Generated by Django 2.0.3 on 2018-04-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0006_auto_20180410_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperativa',
            name='agencia',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
