# Generated by Django 2.0.3 on 2018-04-21 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0006_auto_20180420_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vida',
            old_name='atividade',
            new_name='atividade_empresa',
        ),
    ]
