# Generated by Django 2.0.3 on 2018-04-17 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0007_auto_20180411_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresarial',
            name='segurado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='agendamento.Segurado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cooperativa',
            name='agencia',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='segurado',
            name='cnpj',
            field=models.CharField(max_length=14),
        ),
    ]
