# Generated by Django 2.0.3 on 2018-04-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0007_auto_20180421_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vida',
            name='IS',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
