# Generated by Django 2.0.3 on 2018-04-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0008_auto_20180417_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresarial',
            name='protocol',
            field=models.TextField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frota',
            name='protocol',
            field=models.TextField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='bem',
            field=models.TextField(max_length=20),
        ),
    ]
