# Generated by Django 2.0.3 on 2018-04-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0009_vida_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vida',
            name='tipo',
            field=models.CharField(max_length=20),
        ),
    ]
