# Generated by Django 2.0.3 on 2018-04-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0010_auto_20180421_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresarial',
            name='final_vigencia',
        ),
        migrations.RemoveField(
            model_name='frota',
            name='final_vigencia',
        ),
        migrations.RemoveField(
            model_name='vida',
            name='final_vigencia',
        ),
        migrations.AlterField(
            model_name='vida',
            name='tipo',
            field=models.CharField(choices=[('GLOBAL', 'Global'), ('ESPECIFICA', 'Específica')], max_length=20),
        ),
    ]
