# Generated by Django 2.0.3 on 2018-04-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0011_auto_20180421_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresarial',
            name='protocol',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vida',
            name='protocol',
            field=models.CharField(max_length=20),
        ),
    ]
