# Generated by Django 2.0.3 on 2018-04-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0013_segurado_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='segurado',
            name='complemento',
            field=models.CharField(default='N/I', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='segurado',
            name='numero',
            field=models.CharField(default=999, max_length=10),
            preserve_default=False,
        ),
    ]
